{% set name = "marko" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marko-{{ version }}.tar.gz
  sha256: 3b323dcd7dd48181871718ac09b3825bc8f74493cec378f2bacaaceec47577d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - marko=marko.cli:main

requirements:
  host:
    - pip
    - python >=3.7
    - pdm-backend
  run:
    - python >=3.7

test:
  imports:
    - marko
  commands:
    - pip check
    - marko --help
  requires:
    - pip

about:
  home: https://pypi.org/project/marko/
  summary: A markdown parser with high extensibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - asford
