{% set name = "marko" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marko-{{ version }}.tar.gz
  sha256: 213c146ba197c1d6bcb06ae3658b7d87e45f6def35c09905b86aa6bb1984eba6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - marko=marko.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - python >={{ python_min }}

test:
  imports:
    - marko
  commands:
    - pip check
    - marko --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/marko/
  summary: A markdown parser with high extensibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - asford
