{% set name = "marko" %}
{% set version = "2.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marko-{{ version }}.tar.gz
  sha256: e29d7e071a3b0cb2f7cc4c500d55f893dc5a45d85a8298dde6cb4e4dffd794d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - marko=marko.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - python >={{ python_min }}

test:
  imports:
    - marko
  commands:
    - pip check
    - marko --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/marko/
  summary: A markdown parser with high extensibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - asford
