{% set name = "marko" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marko-{{ version }}.tar.gz
  sha256: 80d7807605b5e103f544df93c21e6f66a0d42dbe953c0dcd5b80d35b704bf170

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - marko=marko.cli:main

requirements:
  host:
    - pip
    - python >=3.6
    - pdm-pep517
  run:
    - python >=3.6

test:
  imports:
    - marko
  commands:
    - pip check
    - marko --help
  requires:
    - pip

about:
  home: https://pypi.org/project/marko/
  summary: A markdown parser with high extensibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - asford
